name: eureka_app
description: A flutter project already setup with common features I use and good practices. The features include google_fonts, fontawesome, translation

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.3
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.6
  firebase_core: 0.5.2+1
  firebase_auth: 0.18.3+1
  font_awesome_flutter: ^8.10.0
  rxdart: ^0.24.1
  flutter_form_builder: ^3.14.1
  flutter_spinkit: ^4.1.2+1
  qr_flutter: ^3.2.0
  flutter_statusbarcolor: ^0.2.3
  fl_chart: ^0.12.0
  flutter_inner_drawer: ^0.5.7+2


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/

