// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show JsonMapper, JsonMapperAdapter, typeOf;
import 'package:eureka_app/data/models/user.dart' as x0 show User;

// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:eureka_app/data/models/user.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 7],
            const <int>[8, 3, 9, 10, 11, 4, 5, 6],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, createdAt, restaurantSelected}) => b
                  ? prefix1.User(
                      createdAt: createdAt,
                      id: id,
                      restaurantSelected: restaurantSelected)
                  : null
            },
            -1,
            0,
            const <int>[],
            const [prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 33797, 0, const prefix0.JsonSerializable(),
            -1, 1, 1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdAt',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'restaurantSelected',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.MethodMirrorImpl(r'toString', 131074, 0, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 6),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1, 2], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 3, 3, const <int>[],
            const <int>[3], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            5,
            5,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'id', 45062, 7, const prefix0.JsonSerializable(),
            -1, 1, 1, const <int>[], const [], null, #id),
        r.ParameterMirrorImpl(
            r'createdAt',
            45062,
            7,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #createdAt),
        r.ParameterMirrorImpl(
            r'restaurantSelected',
            45062,
            7,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #restaurantSelected),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            8,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            9,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.User,
        String,
        DateTime,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'createdAt': (dynamic instance) => instance.createdAt,
        r'restaurantSelected': (dynamic instance) => instance.restaurantSelected
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void _initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}

final mainAdapter = JsonMapperAdapter(
    title: 'mainAdapter',
    url: 'package:eureka_app/main.dart',
    valueDecorators: {
      typeOf<List<x0.User>>(): (value) => value.cast<x0.User>(),
      typeOf<Set<x0.User>>(): (value) => value.cast<x0.User>()
    },
    enumValues: {});

JsonMapper initializeJsonMapper(
    {Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, mainAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}
