// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show JsonMapper, JsonMapperAdapter, typeOf;
import 'package:eureka_app/data/models/restaurant.dart' as x0 show Restaurant;
import 'package:eureka_app/data/models/role.dart' as x1 show Role;
import 'package:eureka_app/data/models/user.dart' as x2 show User;

// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:eureka_app/data/models/restaurant.dart' as prefix2;
import 'package:eureka_app/data/models/role.dart' as prefix3;
import 'package:eureka_app/data/models/user.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 12, 16],
            const <int>[17, 12, 18, 19, 20, 13, 14, 15],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, createdAt, restaurantSelected}) => b
                  ? prefix1.User(
                      createdAt: createdAt,
                      id: id,
                      restaurantSelected: restaurantSelected)
                  : null
            },
            -1,
            0,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'Restaurant',
            r'.Restaurant',
            7,
            1,
            const prefix0.JsonSerializable(),
            const <int>[3, 4, 5, 6, 7, 8, 21, 28],
            const <int>[17, 21, 18, 19, 20, 22, 23, 24, 25, 26, 27],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (
                      {id,
                      name,
                      description,
                      tables = 1,
                      createdAt,
                      createdBy}) =>
                  b
                      ? prefix2.Restaurant(
                          createdAt: createdAt,
                          createdBy: createdBy,
                          description: description,
                          id: id,
                          name: name,
                          tables: tables)
                      : null
            },
            -1,
            1,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'UserRole',
            r'.UserRole',
            7,
            2,
            const prefix0.JsonSerializable(),
            const <int>[9, 10, 11, 32],
            const <int>[17, 33, 18, 19, 20, 29, 30, 31],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, role, restaurant}) => b
                  ? prefix3.Role(id: id, restaurant: restaurant, role: role)
                  : null
            },
            -1,
            2,
            const <int>[],
            const [prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 33797, 0, const prefix0.JsonSerializable(),
            -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdAt',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'restaurantSelected',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(r'id', 33797, 1, const prefix0.JsonSerializable(),
            -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'name',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'description',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'tables',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdAt',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdBy',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(r'id', 33797, 2, const prefix0.JsonSerializable(),
            -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'role',
            33797,
            2,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'restaurant',
            33797,
            2,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.MethodMirrorImpl(r'toString', 131074, 0, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 13),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 14),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 15),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1, 2], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 6, 6, const <int>[],
            const <int>[3], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            7,
            7,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'toString', 131074, 1, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 22),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 23),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 24),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 6, 25),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 7, 26),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 8, 27),
        r.MethodMirrorImpl(
            r'',
            0,
            1,
            -1,
            1,
            1,
            const <int>[],
            const <int>[5, 6, 7, 8, 9, 10],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 9, 29),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 10, 30),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 11, 31),
        r.MethodMirrorImpl(
            r'',
            0,
            2,
            -1,
            2,
            2,
            const <int>[],
            const <int>[11, 12, 13],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id',
            45062,
            16,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'createdAt',
            45062,
            16,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #createdAt),
        r.ParameterMirrorImpl(
            r'restaurantSelected',
            45062,
            16,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #restaurantSelected),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            17,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            18,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            45062,
            28,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'name',
            45062,
            28,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #name),
        r.ParameterMirrorImpl(
            r'description',
            45062,
            28,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #description),
        r.ParameterMirrorImpl(
            r'tables',
            47110,
            28,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            1,
            #tables),
        r.ParameterMirrorImpl(
            r'createdAt',
            45062,
            28,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #createdAt),
        r.ParameterMirrorImpl(
            r'createdBy',
            45062,
            28,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #createdBy),
        r.ParameterMirrorImpl(
            r'id',
            45062,
            32,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'role',
            45062,
            32,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #role),
        r.ParameterMirrorImpl(
            r'restaurant',
            45062,
            32,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #restaurant)
      ],
      <Type>[
        prefix1.User,
        prefix2.Restaurant,
        prefix3.Role,
        String,
        DateTime,
        int,
        bool,
        Type,
        Object,
        Invocation
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'createdAt': (dynamic instance) => instance.createdAt,
        r'restaurantSelected': (dynamic instance) =>
            instance.restaurantSelected,
        r'name': (dynamic instance) => instance.name,
        r'description': (dynamic instance) => instance.description,
        r'tables': (dynamic instance) => instance.tables,
        r'createdBy': (dynamic instance) => instance.createdBy,
        r'role': (dynamic instance) => instance.role,
        r'restaurant': (dynamic instance) => instance.restaurant
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void _initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}

final mainAdapter = JsonMapperAdapter(
    title: 'mainAdapter',
    url: 'package:eureka_app/main.dart',
    valueDecorators: {
      typeOf<List<x0.Restaurant>>(): (value) => value.cast<x0.Restaurant>(),
      typeOf<Set<x0.Restaurant>>(): (value) => value.cast<x0.Restaurant>(),
      typeOf<List<x1.Role>>(): (value) => value.cast<x1.Role>(),
      typeOf<Set<x1.Role>>(): (value) => value.cast<x1.Role>(),
      typeOf<List<x2.User>>(): (value) => value.cast<x2.User>(),
      typeOf<Set<x2.User>>(): (value) => value.cast<x2.User>()
    },
    enumValues: {});

JsonMapper initializeJsonMapper(
    {Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, mainAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}
